### ISSUE TITLE
'getOutputOfSysCommand' is not defined

### ISSUE THREAD

**Issue by gotofritz** [dennishall/Sublime-Text-Subversion-plug-in#1]
Hi. I have followed installation instructions but when I try any of the commands I get an alert saying 

'getOutputOfSysCommand' is not defined

**Comment by dennishall** [comment]
Hello gotofritz. Thanks for trying this plugin. Sorry you're experiencing problems with it. I've only tested it on mac. When I get home, I'll try it on pc. One thing comes to mind though: Please make sure "svn" works from commandline. Open "command prompt" and just type "svn" and hit enter. If it says unrecognized command, you need sliksvn or similar.

This was really only intended for mac/linux, since I think the "tortoise helpers" sublimetext plugin is probably more appropriate for windows folks. But I'm happy to try to make this more windows-friendly.

**Comment by gotofritz** [comment]
Hi, thanks for your comments. Forgot to say: I am also on OS X (Snow Leopard).
I have svn on the command line, and Python 2.7.2

**Comment by dennishall** [comment]
Oh, and you're running sublimetext 2?

**Comment by dennishall** [comment]
I just updated the readme to reflect that this is for Sublime Text 2. (It's probably not compatible with 1.x.)

**Comment by gotofritz** [comment]
Yep, Sublime Text 2, latest build

**Comment by dennishall** [comment]
Must be Python 2.7.2 vs. 2.6.1 (what I have). I don't really know python, I just assembled what I needed from other examples and a bit of reading the Sublime Text 2 plugin API.

**Comment by gotofritz** [comment]
OK thanks, I'll see if I can fix the code myself, but I also am a Python noob

**Comment by dennishall** [comment]
Burriko submitted a patch that fixes this. It's merged now. If you can confirm, please let me know. If you can also close this issue once confirmed, please do. Thanks!

**Comment by gotofritz** [comment]
Hi, that seems to be doing the job, thanks a lot
